### PR TITLE
Fix NullPointerException: #175

### PR DESCRIPTION
**Pull request by NeoP5**
Fixes a NPE raised during initialization of Moskito.

Related Ticket is #175

### CODE REVIEW

**Comment by dvayanu** [comment]
Hi Jan,
is your issue by any chance the same as here: 
https://jira.opensource.anotheria.net/browse/MSK-463 ?

Because if so, we already have another fix for it. It seems to be a circular issue in the initialization sequence. I still kindof wandering how your fix is working, cause it seems to me be syntactically the same as the 'unfixed' version.

**Comment by NeoP5** [comment]
Hi, don’t have an account in your Jira yet.
Can not tell you if this is the same issue. 

Syntactically there is a big difference. 
This is a singleton class... and the fix changes the class to implement the Singleton design pattern using lazy initialization method. This way getInstance can never return null. Before this was 
Possible. 

A private empty constructor should be added to all singletons to avoid external instantiation. 

See: https://www.journaldev.com/1377/java-singleton-design-pattern-best-practices-examples

**Comment by dvayanu** [comment]
JIRA is free to register. 
This class already had a private constructor. I will test your commit, but personally I think it will end up with actually TWO instances of the AccumulatorRepository. Problem, why this happens in first place in wildfly (I assume you have wildfly) is that the initialization sequence in wildfly seem to be different from tomcat or other containers. 
The context listener SetupPreconfiguredAccumulators is initialized first, which then tries to add an accumulator, AccumulatorRepository is created, then in the constructor of the repository a builtinproducer sequence is triggered, which tries to access the AccumulatorRegistry instance, which is being constructed at the same point and this fails. The only way this fix works, is if the AccumulatorRepository.getInstance() actually creates a second instance. But in this case the error-related accumulators won't be added and will be invisible. 
We solved this issue in the commit https://github.com/anotheria/moskito/commit/bb7cc6bf2690e2a7211ebda5430973cc67aba13c by allowing the built-in provider to fully initialize _before_ anything creates an accumulator. Not the nicest of fixes, but it works. 
The better idea would probably be to eliminate the possibility of circular dependencies altogether. (moving auto-creation of accumulator to another execution stack or something). 

That being said, I'll check if the proposed code actually leads to a double AccumulatorRepository and we'll look from there. Cheers.

**Comment by dvayanu** [comment]
I've tested and it works. However two issues:
first) your code contains illegal characters, that prevent javac from building:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project moskito-core: Compilation failure: Compilation failure:
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[39,77] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[39,78] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[39,79] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[40,19] not a statement
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[40,37] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[40,39] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[40,40] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[40,41] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[41,66] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[41,67] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[41,68] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[42,18] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[42,19] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[43,33] illegal character: '\u00a0'
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[47,9] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[47,40] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,30] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,62] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,63] illegal start of type
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,65] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,72] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,79] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[52,89] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[76,37] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[76,59] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[83,9] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[83,49] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[87,9] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[87,45] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[87,67] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[94,9] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[94,17] illegal start of expression
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[94,32] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[115,47] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[115,74] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[134,15] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[144,45] ';' expected
[ERROR] /private/tmp/g/moskito/moskito-core/src/main/java/net/anotheria/moskito/core/accumulation/AccumulatorRepository.java:[147,2] reached end of file while parsing
[ERROR] -> [Help 1]

2) You should add volatile to INSTANCE declaration, otherwise its not thread safe (two threads accessing getInstance simultaneously will create two instances) 

If you can fix both issues, we will happily accept the pull request.
Thank you

**Comment by NeoP5** [comment]
Hello @dvayanu ,

sorry for the delay.
The requested changes have now been pushed.

Best,
Neo

**Comment by dvayanu** [comment]
thanx merged and closed

**Pull request merged**
