### PR TITLE
MSK-293 Server Selector in inspect throws 500 Error

### PR DESCRIPTION
**Pull request by Kseniia1992**

### CODE REVIEW

**Comment by dvayanu** [comment]
Hi Ksenia,
question:
I understand that setting session explicitely can help, but why was the session null in first place?

**Comment by Kseniia1992** [comment]
I think that the session was null because SelectServerAction didn't extend BaseMoskitoUIAction.

**Comment by dvayanu** [comment]
but where is the session set?

**Comment by Kseniia1992** [comment]
CurrentSession is set in BaseMoskitoUIAction.java, in method preProcess :
	MoSKitoWebUIContext context = MoSKitoWebUIContext.getCallContextAndReset();
        context.setCurrentSession(req.getSession());

And class MoSKitoWebUIContext.java has method :
       public void setCurrentSession(HttpSession currentSession) {
		this.currentSession = currentSession;
	}

**Comment by dvayanu** [comment]
Question then, shouldn't SelectServerAction extend BaseMoSKitoUIAction then?

**Comment by Kseniia1992** [comment]
I think , it should.

**Comment by dvayanu** [comment]
os maybe this is the better fix than?

**Comment by Kseniia1992** [comment]
I will fix.

**Pull request closed without merging**
