### PR TITLE
Please add this to provide Java 8 compiler support

### PR DESCRIPTION
**Pull request by dheid**
Due to an incompatibility with the aspectj maven plugin version 1.4, you cannot build Moskito AOP and the SQL integration with a Java 8 compiler. Since Java 7 is no longer supported broadly by Oracle, please consider this update to the newest plugin version (1.8) and the aspectj compiler 1.8.7.

I also tried to centralize some versioning properties to the parent POM to deny multiple versions of some dependencies within the Moskito project.

Thanks again for your support and this great tool!

### CODE REVIEW

**Comment by dvayanu** [comment]
Hi Daniel,
thanks again for your contributions ;-)
I just started to look into it. 
Question 1: you moved part of the code in ProxyUtils in separate method, but I didn't see that you use it somewhere else. Also the method is public and not javadoc-ed (I know we miss javadocs here and there, but our checkstyle rules actually require it, and we try to reduce the red lines:-))
https://jenkins.opensource.anotheria.net/jenkins/view/MoSKito%20CI/job/moskito-core_ci/

Question 2: You removed moskitoplugins. Did it prevent you from building? The module is a new one, and is not part of opensource stack. We included it in a special profile so we can package it in final version, but it should build without this module. 

Question 3: I've seen you changed String concatenation to appends at some points (I think you didn't commit added it to pull request yet, but i was looking at your branch. 
I am actually unsure if the compiler detects such code automatically:

call.append(" ERR "+t.getMessage()); will be transformed into call.append(new StringBuilder(" ERR ").append(t.getMessage().toString())

What I am not sure about is if the HotSpot is able to detect such code and correct it automatically.

Anyway it is probably better to write it in one line:
call.append(" ERR ").append(t.getMessage());

regards
Leon

**Comment by dheid** [comment]
Hey Leon,

you're absolutely right. I did some enhancements after thinking about your questions.

ad 1:
I extracted the code into a separate method primarily to ease the testing of my changes in the newly introduced test class ProxyUtilsTest. The missing javadoc is added here: 4f41057

ad 2:
Ok, this was a mistake, sorry. I reverted the commit. It's now included again. fa0c727

ad 3:
I found nothing about this issue in the web. It could be error prone to convert a string concatenation  automatically. But at least I converted it to one line as you recommended. db3ae8c

Best wishes

Daniel

**Comment by dheid** [comment]
I did some more changes according to recommendations of the IDE code inspector, which I think could boost the performance in the sense of micro-optimization.

Consider these changes as optional. If you find them useful, feel free to merge them. But I don't mind if you skip them.

**Comment by dvayanu** [comment]
I've merged the pull request, funny, it refuses to build locally:
Failed tests: 
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly1:104->assertFormatting:150 
Expected: is "-1.235"
     but: was "-1,235"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly2:109->assertFormatting:150 
Expected: is "-12.346"
     but: was "-12,346"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly3:114->assertFormatting:150 
Expected: is "-123.457"
     but: was "-123,457"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly4:119->assertFormatting:150 
Expected: is "-12345.679"
     but: was "-12345,679"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly5:124->assertFormatting:150 
Expected: is "-123456.789"
     but: was "-123456,789"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly6:129->assertFormatting:150 
Expected: is "-1234567.890"
     but: was "-1234567,890"
  DoubleValueAOTest.longNegativeDoubleIsFormattedCorrectly7:134->assertFormatting:150 
Expected: is "-12345678.900"
     but: was "-12345678,900"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly1:69->assertFormatting:150 
Expected: is "1.235"
     but: was "1,235"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly2:74->assertFormatting:150 
Expected: is "12.346"
     but: was "12,346"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly3:79->assertFormatting:150 
Expected: is "123.457"
     but: was "123,457"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly4:84->assertFormatting:150 
Expected: is "12345.679"
     but: was "12345,679"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly5:89->assertFormatting:150 
Expected: is "123456.789"
     but: was "123456,789"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly6:94->assertFormatting:150 
Expected: is "1234567.890"
     but: was "1234567,890"
  DoubleValueAOTest.longPositiveDoubleIsFormattedCorrectly7:99->assertFormatting:150 
Expected: is "12345678.900"
     but: was "12345678,900"
  DoubleValueAOTest.nANIsFormattedCorrectly:14->assertFormatting:150 
Expected: is "0.000"
     but: was "0,000"
  DoubleValueAOTest.piIsFormattedCorrectly:144->assertFormatting:150 
Expected: is "3.142"
     but: was "3,142"
  DoubleValueAOTest.shortPositiveDoubleIsFormattedCorrectly1:59->assertFormatting:150 
Expected: is "1.000"
     but: was "1,000"
  DoubleValueAOTest.shortPositiveDoubleIsFormattedCorrectly2:64->assertFormatting:150 
Expected: is "47.110"
     but: was "47,110"
  DoubleValueAOTest.smallNegativeDoubleIsFormattedCorrectly:49->assertFormatting:150 
Expected: is "-0.123"
     but: was "-0,123"
  DoubleValueAOTest.smallPositiveDoubleIsFormattedCorrectly:44->assertFormatting:150 
Expected: is "0.123"
     but: was "0,123"
  DoubleValueAOTest.veryLongPositiveDoubleIsFormattedCorrectly7:139->assertFormatting:150 
Expected: is "9223372036854776.000"
     but: was "9223372036854776,000"
  DoubleValueAOTest.veryShortPositiveDoubleIsFormattedCorrectly7:54->assertFormatting:150 
Expected: is "0.000"
     but: was "0,000"
  DoubleValueAOTest.wholeNumberIsFormattedCorrectly:39->assertFormatting:150 
Expected: is "42.000"
     but: was "42,000"
  DoubleValueAOTest.zeroIsFormattedCorrectly1:29->assertFormatting:150 
Expected: is "0.000"
     but: was "0,000"
  DoubleValueAOTest.zeroIsFormattedCorrectly2:34->assertFormatting:150 
Expected: is "0.000"
     but: was "0,000"

but it builds on jenkins. Must be something with local config.

**Comment by dvayanu** [comment]
Ok I disabled DoubleValueAOTest and DoubleBeanTest since they rely on local settings (. or ,  as separator) and are unstable.
Interesting that the later was an old test, so some behavior changed in the system, we'll see if everything works still.

small another point: removed public from mergeInterfaces method in ProxyUtils, if you make methods just for testing, they can be package local, not necessary public.

regards
L

**Pull request merged**
